version: '3.9'

services:
  api:
    build:
      context: .
      dockerfile: ./deploy/Dockerfile
      target: prod
    image: MultiModal:${MULTIMODAL_VERSION:-latest}
    restart: always
    env_file:
    - .env
    depends_on:
      redis:
        condition: service_healthy
    environment:
      MULTIMODAL_HOST: 0.0.0.0
      MULTIMODAL_DB_FILE: /db_data/db.sqlite3
      MULTIMODAL_REDIS_HOST: MultiModal-redis
    volumes:
    - MultiModal-db-data:/db_data/

  redis:
    image: bitnami/redis:6.2.5
    hostname: "MultiModal-redis"
    restart: always
    environment:
      ALLOW_EMPTY_PASSWORD: "yes"
    healthcheck:
      test: redis-cli ping
      interval: 1s
      timeout: 3s
      retries: 50



volumes:
  MultiModal-db-data:
    name: MultiModal-db-data
